version: '3.5'
services:
  config-service:
    container_name: config-service
    build: config-service
    ports:
    - 8001:8001

  registry:
    container_name: registry
    restart: always
    build: registry
    ports:
    - 8761:8761
    depends_on:
      - config-service

  gateway:
    container_name: gateway
    restart: always
    build: gateway
    ports:
    - 8989:8989
    depends_on:
      - config-service
      - registry

  account-service:
    container_name: account-service
    restart: always
    build: account-service
    ports:
    - 8081:8081
    depends_on:
      - config-service
      - registry
      - gateway

  bill-service:
    container_name: bill-service
    restart: always
    build: bill-service
    ports:
    - 8082:8082
    depends_on:
      - config-service
      - registry
      - gateway

  deposit-service:
    container_name: deposit-service
    restart: always
    build: deposit-service
    ports:
    - 8086:8086
    depends_on:
      - config-service
      - registry
      - gateway

  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: rabbitmq
    labels:
      NAME: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    depends_on:
      - config-service
      - registry
      - gateway

  notification-service:
    container_name: notification-service
    restart: always
    build: notification-service
    ports:
    - 9999:9999
    depends_on:
      - config-service
      - registry
      - gateway
      - rabbitmq
